version: '3.8'

services:

  server:
    image: nginx:1.21.6-alpine
    container_name: server
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src/:/var/www/
    working_dir: /var/www/
    depends_on:
      - php
    networks:
      - docker

  php-8:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-8
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../src:/var/www/
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - docker

  db:
    image: mariadb:10.6
    container_name: db
    expose:
      - 3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./db:/var/lib/mysql
    depends_on:
      - php-8
    networks:
      - docker


networks:
  docker:
    driver: bridge